on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0

      - name: Build With Gradle
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease --refresh-dependencies

      - name: Prepare App
        run: |
          mkdir -p ${{ github.workspace }}/apk/
          find ./app/build/outputs/apk/ -type f -name "*.apk" -exec mv {} ${{ github.workspace }}/apk/ \;

      - name: Upload App To Artifact
        uses: actions/upload-artifact@v4.2.0
        with:
          name: com.github.tvbox.osc
          path: ${{ github.workspace }}/apk/app-release.apk
